### ISSUE TITLE
TextView Scroll to bottom unnecessary in case of Edit 

### ISSUE THREAD

**Issue by dsngeu** [Datt1994/DPTagDetectionTextView#10]
Step 1 = Type some words in TextView like 10-12 lines
Step 2 = now add/edit some text in top/middle in textView 
step 3 = when you will type new words in each word textview scroll to bottom 
@Datt1994

**Comment by dsngeu** [comment]
@Datt1994 is there any solution for this ?

**Comment by Datt1994** [comment]
@dsngeu check updated repo.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
