### ISSUE TITLE
search String can't contain spaces & not being able to delete whole tag at once

### ISSUE THREAD

**Issue by Akiladilsh** [Datt1994/DPTagDetectionTextView#13]
Awesome work on the pod. is there a way to get spaces with in search string ex:-  "Date  " words after a space won't get added to the search term. seems this happens due match data function and is there a way to delete whole tag. Thanks in advance @Datt1994

**Comment by Datt1994** [comment]
@Akiladilsh,

Set `allowsHashTagUsingSpace` property to `false` may solve your issue.
`tagTextView.allowsHashTagUsingSpace = false`

**Comment by Datt1994** [comment]
@Akiladilsh,

For spaces to work, you need to change 2 lines.
1st,
         
 ```
  else if /*char == space ||*/ char == lineBrak {
                tagable = false
                break
            }
```
remove char == space condition
2nd,
```
    private var tagRegex: NSRegularExpression {
        try! NSRegularExpression(pattern: "(\(mentionSymbol)|\(hashTagSymbol))([^\\K]+)")
    }
```
replace `tagRegex` with above.
I will try to add this in next release till then just modify above 2 line.

**Comment by Akiladilsh** [comment]
@Datt1994  thanks for solution.
