### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dsngeu** [Datt1994/DPTagDetectionTextView#5]
step 1 - open keyboard 
step 2 -  tap on suggested words
step 3 - tap on send button and clear textview text
step 4 - type new word --> crash 

Crash At: 
for rag in arrRange.reversed() {
            newString.insert(contentsOf: tagPostfix, at: rag.upperBound) // Crash line
            newString.insert(contentsOf: tagPrefix, at: rag.lowerBound)
        }

**Comment by dsngeu** [comment]
Crash has been resolved on send button tap call clearTagTextView()

private func clearTagTextView() {
        
        txtMain.text = ""
        txtMain.arrTags = []
        arrTagedUser.removeAll()
        txtMain.arrRange = []
    }

**Comment by Datt1994** [comment]
@dsngeu Check updated repo.
