### ISSUE TITLE
Wrong position placement of mention keyword

### ISSUE THREAD

**Issue by dsngeu** [Datt1994/DPTagDetectionTextView#7]
Step 1 - type some text and press space 
step 2 - press @ then auto suggestion keyword will appear - choose any auto suggestion keyword
step 3 - press @ then choose any mention user from UITableview 
UITextview will have wrong text and wrong position of current mention user
@Datt1994  can you please check this.

or is there any way to tern off autosuggestion when list of user appear and then tern on auto suggestion when UITableView hide
@Datt1994

**Comment by dsngeu** [comment]
is there any way to bind userId with Name 
like we have arrRange with we don't have any way to get associated User id.
because there may b chances of User listing may have 2-3 user with same name.
@Datt1994

**Comment by Datt1994** [comment]
> Step 1 - type some text and press space
> step 2 - press @ then auto suggestion keyword will appear - choose any auto suggestion keyword
> step 3 - press @ then choose any mention user from UITableview
> UITextview will have wrong text and wrong position of current mention user
> @Datt1994 can you please check this.
> 
> or is there any way to tern off autosuggestion when list of user appear and then tern on auto suggestion when UITableView hide
> @Datt1994

I am not getting this issue by my side so please provide with more elaborated example or video.

**Comment by Datt1994** [comment]
> is there any way to bind userId with Name
> like we have arrRange with we don't have any way to get associated User id.
> because there may b chances of User listing may have 2-3 user with same name.
> @Datt1994

Check Updated repo.
